import { WeeklyTimesheet } from "@/types/timesheet";

export const timesheets: WeeklyTimesheet[] = [
  {
    id: "week-1",
    weekNumber: 1,
    startDate: "2024-01-01",
    endDate: "2024-01-05",
    status: "completed",
    totalHours: 40,
    entries: [
      {
        id: "entry-1",
        date: "2024-01-01",
        projectId: "project-1",
        projectName: "Homepage Development",
        workType: "Development",
        description: "Homepage layout and responsive implementation",
        hours: 8,
      },
      {
        id: "entry-2",
        date: "2024-01-02",
        projectId: "project-1",
        projectName: "Homepage Development",
        workType: "Development",
        description: "Homepage components and styling",
        hours: 8,
      },
      {
        id: "entry-3",
        date: "2024-01-03",
        projectId: "project-2",
        projectName: "Dashboard Development",
        workType: "Development",
        description: "Dashboard initial implementation",
        hours: 8,
      },
      {
        id: "entry-4",
        date: "2024-01-04",
        projectId: "project-2",
        projectName: "Dashboard Development",
        workType: "Development",
        description: "Dashboard table implementation",
        hours: 8,
      },
      {
        id: "entry-5",
        date: "2024-01-05",
        projectId: "project-1",
        projectName: "Homepage Development",
        workType: "Testing",
        description: "Responsive testing and bug fixes",
        hours: 8,
      },
    ],
  },

  {
    id: "week-2",
    weekNumber: 2,
    startDate: "2024-01-08",
    endDate: "2024-01-12",
    status: "completed",
    totalHours: 40,
    entries: [
      {
        id: "entry-6",
        date: "2024-01-08",
        projectId: "project-2",
        projectName: "Dashboard Development",
        workType: "Development",
        description: "Timesheet dashboard development",
        hours: 8,
      },
      {
        id: "entry-7",
        date: "2024-01-09",
        projectId: "project-2",
        projectName: "Dashboard Development",
        workType: "Development",
        description: "Timesheet table and filters",
        hours: 8,
      },
      {
        id: "entry-8",
        date: "2024-01-10",
        projectId: "project-1",
        projectName: "Homepage Development",
        workType: "Development",
        description: "Homepage improvements",
        hours: 8,
      },
      {
        id: "entry-9",
        date: "2024-01-11",
        projectId: "project-3",
        projectName: "Mobile Application",
        workType: "Development",
        description: "Mobile layout implementation",
        hours: 8,
      },
      {
        id: "entry-10",
        date: "2024-01-12",
        projectId: "project-3",
        projectName: "Mobile Application",
        workType: "Testing",
        description: "Mobile testing and fixes",
        hours: 8,
      },
    ],
  },

  {
    id: "week-3",
    weekNumber: 3,
    startDate: "2024-01-15",
    endDate: "2024-01-19",
    status: "incomplete",
    totalHours: 32,
    entries: [
      {
        id: "entry-11",
        date: "2024-01-15",
        projectId: "project-1",
        projectName: "Homepage Development",
        workType: "Development",
        description: "Homepage improvements",
        hours: 8,
      },
      {
        id: "entry-12",
        date: "2024-01-16",
        projectId: "project-2",
        projectName: "Dashboard Development",
        workType: "Development",
        description: "Dashboard components",
        hours: 8,
      },
      {
        id: "entry-13",
        date: "2024-01-17",
        projectId: "project-2",
        projectName: "Dashboard Development",
        workType: "Development",
        description: "Dashboard responsive layout",
        hours: 8,
      },
      {
        id: "entry-14",
        date: "2024-01-18",
        projectId: "project-3",
        projectName: "Mobile Application",
        workType: "Development",
        description: "Mobile application updates",
        hours: 8,
      },
    ],
  },

  {
    id: "week-4",
    weekNumber: 4,
    startDate: "2024-01-22",
    endDate: "2024-01-26",
    status: "completed",
    totalHours: 40,
    entries: [
      {
        id: "entry-15",
        date: "2024-01-22",
        projectId: "project-1",
        projectName: "Homepage Development",
        workType: "Development",
        description: "Homepage development",
        hours: 8,
      },
      {
        id: "entry-16",
        date: "2024-01-23",
        projectId: "project-1",
        projectName: "Homepage Development",
        workType: "Development",
        description: "Homepage components",
        hours: 8,
      },
      {
        id: "entry-17",
        date: "2024-01-24",
        projectId: "project-2",
        projectName: "Dashboard Development",
        workType: "Development",
        description: "Dashboard development",
        hours: 8,
      },
      {
        id: "entry-18",
        date: "2024-01-25",
        projectId: "project-2",
        projectName: "Dashboard Development",
        workType: "Testing",
        description: "Dashboard testing",
        hours: 8,
      },
      {
        id: "entry-19",
        date: "2024-01-26",
        projectId: "project-3",
        projectName: "Mobile Application",
        workType: "Testing",
        description: "Mobile application testing",
        hours: 8,
      },
    ],
  },
  {
    id: "week-5",
    weekNumber: 5,
    startDate: "2024-01-29",
    endDate: "2024-02-02",
    status: "missing",
    totalHours: 0,
    entries: [],
  },
];